on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'env'
        required: true
        default: 'dev'
      branch:
        description: 'branch'
        required: true
        default: 'main'

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      RUN_ID: ${{ github.run_id }}
      environment: ${{ github.event.inputs.environment || 'dev' }}
      REPO_NAME: 'lights5.orders-service'

    steps:
        # checkout
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set JAVA Version
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '19'
          components: 'native-image'
          run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
            gu --version
            native-image --version


      - name: JAVA Version
        run: java -version

      - name: Compile & Build Native Executable
        run: mvn -DskipTests -Pnative native:compile

      - name: Build, tag, and push the image to Docker Hub
        id: build-image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

        run: |
          # Build a docker container and push it to DockerHub
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          mvn spring-boot:build-image
          echo "Pushing image to Docker Hub..."
          docker push $DOCKER_USER/${{ github.repository }}:${{ env.environment }}-${{ env.RUN_ID }}
